#!/usr/bin/env python3
"""
check_report.py — structural checker for SIS #01.   DO NOT EDIT THIS FILE.

    cd sis-01
    python tests/check_report.py            # human-readable, ends with a SUMMARY line
    python tests/check_report.py --json     # machine-readable, for the grading pipeline

It checks SHAPE, never QUALITY. It counts words, finds your sections, your three AI
exchanges and your two evidence tables, and checks that the prompts are the ones the
assignment gives. It cannot tell whether your analysis is right, whether a source says
what you claim it says, or whether you understood anything. Those are graded by a person.

Verdicts:
    PASS   the check is satisfied
    FAIL   the thing is there but wrong: a word count outside its range, a table with one
           row, a prompt with a [bracketed field] never replaced
    ERROR  the thing cannot be checked at all: report.md missing, a section heading deleted

A FAIL you report honestly in submission.yml costs you nothing extra.
A number you invent costs the whole workflow criterion.

Exit codes: 0 = no FAIL and no ERROR · 1 = at least one FAIL or ERROR ·
            2 = report.md missing · 3 = run from the wrong directory.

Standard library only.
"""

import argparse
import json
import os
import re
import sys
from datetime import date

REPORT = "report.md"

SECTIONS = {
    1: "Scenario",
    2: "Analysis",
    3: "Review",
    4: "Conclusion",
    5: "Reflection",
    6: "References",
    7: "Appendix A",
    8: "Appendix B",
    9: "Appendix C",
}

WORD_RANGES = {            # section -> (min, max), from the assignment's report structure
    1: (100, 150),
    2: (350, 400),
    3: (250, 300),
    4: (100, 150),
}
MAIN_TOTAL = (800, 1000)   # sections 1-4; references and appendix excluded
REFLECTION = (150, 200)    # section 5, separate from the main total

SCENARIO_LABELS = ("Question", "Users", "Problem", "Constraints", "Risk", "Assumptions")

EXCHANGES = ("B1", "B2", "B3")
MIN_RESPONSE_WORDS = {"B1": 150, "B2": 100, "B3": 150}

# Fixed phrases from the three prompts in the assignment. Each must survive in the prompt
# you actually sent: they are how the checker knows you used the given prompt and not
# your own paraphrase of it. Case and whitespace are ignored.
ANCHORS = {
    "B1": ("act as a software engineering tutor",
           "separate facts from assumptions",
           "do not invent quotations, references or page numbers"),
    "B2": ("identify inaccuracies, missing reasoning, vague claims and unsupported assumptions",
           "include a counterexample or alternative interpretation",
           "do not rewrite the answer yet"),
    "B3": ("revise the draft using my review decisions and source notes",
           "show what you changed and why",
           "use only the sources i supplied"),
}

# The bracketed fields of the three prompts. Every one must be replaced by your own text.
BRACKET_FIELDS = (
    "[number and question]", "[users, problem, constraints and risk]", "[five points]",
    "[paste]", "[paste the full prompt a response]",
    "[accepted or rejected feedback and reasons]", "[notes with citations]",
)

BARE_TOOL_NAMES = {
    "chatgpt", "gpt", "claude", "gemini", "copilot", "github copilot", "deepseek",
    "grok", "mistral", "llama", "qwen", "perplexity", "cursor", "openai", "anthropic",
}
MODEL_HIDDEN = "not displayed"
HAS_DIGIT = re.compile(r"\d")

DECISIONS = ("keep", "qualify", "reject")
LOCATOR = re.compile(
    r"(\bp{1,2}\.\s*\d)|(\bpages?\s*\d)|(\bslides?\s*#?\d)|(\bsection\s*\d)|(§\s*\d)"
    r"|(\bch(apter|\.)?\s*\d)|(\bprinciple\s*\d)|(https?://\S+)",
    re.IGNORECASE,
)
URL = re.compile(r"https?://[^\s|)>\]]+", re.IGNORECASE)
ACCESS_DATE = re.compile(r"(\d{4}-\d{2}-\d{2})|(\baccessed\b)", re.IGNORECASE)
ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

PLACEHOLDER = re.compile(r"\(write here[^)]*\)|\(paste here\)", re.IGNORECASE)
COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
HEADING = re.compile(r"^##\s+(\d+)\.\s*(.*)$")
FENCE = re.compile(r"^(`{3,}|~{3,})")
STOPWORDS = set("""
a an the and or but if of to in on at for from by with without into onto over under is are was
were be been being it its this that these those they them their there here as not no can could
should would will may might must do does did have has had i me my we our you your he she his her
who whom which what when where why how than then so such very more most less least also only
just about each other some any all both one two three first second new use used using
""".split())


# --------------------------------------------------------------------------- helpers


def words(text):
    """Words as a reader counts them: tokens with at least one letter or digit."""
    text = COMMENT.sub(" ", text)
    text = re.sub(r"[*_`#>|]", " ", text)
    return [t for t in text.split() if re.search(r"[0-9A-Za-zА-Яа-яЁёӘәҒғҚқҢңӨөҰұҮүҺһІі]", t)]


def norm(text):
    return re.sub(r"\s+", " ", (text or "").lower()).strip()


def content_words(text):
    return {w for w in re.findall(r"[a-zA-Zа-яА-Я]{5,}", (text or "").lower()) if w not in STOPWORDS}


def shingles(text, n=6):
    toks = re.findall(r"\w+", (text or "").lower())
    return {" ".join(toks[i:i + n]) for i in range(max(0, len(toks) - n + 1))}


def split_sections(text):
    """{number: body} for every `## N.` heading, comments removed, in file order."""
    text = COMMENT.sub("", text)
    found, order, current, buf, in_fence = {}, [], None, [], None
    for line in text.splitlines():
        fence = FENCE.match(line.strip())
        if fence:
            mark = fence.group(1)
            if in_fence is None:
                in_fence = mark
            elif mark[0] == in_fence[0] and len(mark) >= len(in_fence) and line.strip() == mark:
                in_fence = None
        m = HEADING.match(line) if in_fence is None else None
        if m:
            if current is not None:
                found[current] = "\n".join(buf)
            current, buf = int(m.group(1)), []
            order.append(current)
            continue
        if current is not None:
            buf.append(line)
    if current is not None:
        found[current] = "\n".join(buf)
    return found, order


def label_value(body, label):
    m = re.search(rf"\*\*{label}:\*\*\s*(.*)", body)
    return m.group(1).strip() if m else None


def fenced_after(body, label):
    """The first fenced block after a line containing **label:**."""
    lines = body.splitlines()
    start = None
    for i, line in enumerate(lines):
        if f"**{label}:**" in line:
            start = i + 1
            break
    if start is None:
        return None
    for i in range(start, len(lines)):
        stripped = lines[i].strip()
        if not stripped:
            continue
        opening = FENCE.match(stripped)
        if not opening:
            return None  # something other than a code block follows the label
        mark = opening.group(1)
        out = []
        for j in range(i + 1, len(lines)):
            s = lines[j].strip()
            if s and s[0] == mark[0] and set(s) == {mark[0]} and len(s) >= len(mark):
                return "\n".join(out)
            out.append(lines[j])
        return "\n".join(out)  # unterminated fence: take the rest
    return None


def split_exchanges(body):
    parts, current, buf = {}, None, []
    in_fence = None
    for line in body.splitlines():
        fence = FENCE.match(line.strip())
        if fence:
            mark = fence.group(1)
            if in_fence is None:
                in_fence = mark
            elif mark[0] == in_fence[0] and line.strip() == mark:
                in_fence = None
        m = re.match(r"^###\s+(B\d+)\b", line) if in_fence is None else None
        if m:
            if current:
                parts[current] = "\n".join(buf)
            current, buf = m.group(1).upper(), []
            continue
        if current:
            buf.append(line)
    if current:
        parts[current] = "\n".join(buf)
    return parts


def meta(block, key):
    m = re.search(rf"^\s*[-*]?\s*\*\*{key}:\*\*\s*(.*)$", block, re.MULTILINE)
    return m.group(1).strip() if m else ""


def table_after(body, heading):
    """Data rows of the first markdown table after a `### heading` line."""
    lines = body.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.match(rf"^###\s+{heading}\b", line, re.IGNORECASE):
            start = i + 1
            break
    if start is None:
        return None
    rows, seen_table = [], False
    for line in lines[start:]:
        s = line.strip()
        if s.startswith("###"):
            break
        if not s.startswith("|"):
            if seen_table and s:
                break
            continue
        seen_table = True
        cells = [c.strip() for c in s.strip("|").split("|")]
        if all(re.fullmatch(r":?-{3,}:?", c) for c in cells if c):
            continue
        rows.append(cells)
    return rows[1:] if rows else []  # drop the header row


def filled(cell):
    return bool(cell) and not PLACEHOLDER.search(cell) and not re.fullmatch(r"\[.*\]", cell)


def model_problem(value):
    v = (value or "").strip()
    if not v or PLACEHOLDER.search(v):
        return "left empty"
    if v.lower() == MODEL_HIDDEN:
        return None
    if v.lower() in BARE_TOOL_NAMES or not HAS_DIGIT.search(v):
        return f"{v!r} is a tool name, not a model — give the exact model and version, or write \"not displayed\""
    return None


# --------------------------------------------------------------------------- the checks


class Results:
    def __init__(self):
        self.rows = []

    def add(self, cid, verdict, message):
        self.rows.append({"id": cid, "verdict": verdict, "message": message})

    def counts(self):
        out = {"PASS": 0, "FAIL": 0, "ERROR": 0}
        for r in self.rows:
            out[r["verdict"]] += 1
        return out


ALL_IDS = (
    ("S1", "all nine numbered sections present"), ("S2", "topic declared"),
    ("W1", "section 1 word count"), ("W2", "section 2 word count"),
    ("W3", "section 3 word count"), ("W4", "section 4 word count"),
    ("W5", "main report total"), ("W6", "reflection word count"),
    ("C1", "scenario labels filled"), ("A1", "initial outline has five points"),
    ("E1", "three exchanges present"), ("E2", "exchange metadata"),
    ("E3", "prompts and responses complete"), ("E4", "the assignment's prompts used"),
    ("E5", "bracketed fields replaced"), ("E6", "Prompt A carries your scenario and outline"),
    ("E7", "Prompt B carries the Prompt A draft"), ("E8", "Prompt C carries the draft"),
    ("V1", "verification table has two complete rows"), ("V2", "every claim has a locator"),
    ("V3", "every decision is keep / qualify / reject"),
    ("L1", "change log has two substantive rows"), ("R1", "references"),
    ("P1", "no template markers left"),
)


def check(text):
    res = Results()
    measured = {}
    sections, order = split_sections(text)

    # S1 — structure
    missing = [n for n in SECTIONS if n not in sections]
    if missing:
        res.add("S1", "ERROR", "missing heading(s): " + ", ".join(f"## {n}. {SECTIONS[n]}" for n in missing)
                + " — restore them from the template; nothing inside them can be checked")
    elif [n for n in order if n in SECTIONS] != sorted(SECTIONS):
        res.add("S1", "FAIL", f"sections out of order: {order}")
    else:
        res.add("S1", "PASS", "sections 1-9 present, in order")

    def body(n):
        return sections.get(n)

    # S2 — topic
    head = COMMENT.sub("", text.split("\n## ", 1)[0])
    m = re.search(r"\*\*Topic:\*\*\s*1\.(10|[1-9])(?![0-9])", head)
    if m:
        measured["topic"] = f"1.{m.group(1)}"
        res.add("S2", "PASS", f"topic {measured['topic']}")
    else:
        measured["topic"] = None
        res.add("S2", "FAIL", "no **Topic:** line with one of 1.1 … 1.10 above section 1")

    # W1-W6 — word counts
    main_total = 0
    for n, cid in zip((1, 2, 3, 4), ("W1", "W2", "W3", "W4")):
        if body(n) is None:
            res.add(cid, "ERROR", f"section {n} is missing")
            continue
        count = len(words(body(n)))
        measured[f"words_s{n}"] = count
        main_total += count
        lo, hi = WORD_RANGES[n]
        verdict = "PASS" if lo <= count <= hi else "FAIL"
        res.add(cid, verdict, f"section {n} ({SECTIONS[n]}): {count} words, range {lo}-{hi}")
    if all(body(n) is not None for n in (1, 2, 3, 4)):
        measured["main_words"] = main_total
        lo, hi = MAIN_TOTAL
        res.add("W5", "PASS" if lo <= main_total <= hi else "FAIL",
                f"main report (sections 1-4): {main_total} words, range {lo}-{hi}")
    else:
        res.add("W5", "ERROR", "cannot total: a main section is missing")
    if body(5) is None:
        res.add("W6", "ERROR", "section 5 is missing")
    else:
        count = len(words(body(5)))
        measured["reflection_words"] = count
        lo, hi = REFLECTION
        res.add("W6", "PASS" if lo <= count <= hi else "FAIL",
                f"reflection: {count} words, range {lo}-{hi}")

    # C1 — scenario labels
    if body(1) is None:
        res.add("C1", "ERROR", "section 1 is missing")
    else:
        bad = []
        for label in SCENARIO_LABELS:
            value = label_value(body(1), label)
            if value is None:
                bad.append(f"{label} (label deleted)")
            elif PLACEHOLDER.search(value) or len(words(value)) < 3:
                bad.append(f"{label} (empty or under 3 words)")
        res.add("C1", "FAIL" if bad else "PASS",
                "scenario: " + (", ".join(bad) if bad else "all six labels filled"))

    # A1 — initial outline
    if body(7) is None:
        res.add("A1", "ERROR", "section 7 is missing")
    else:
        items = re.findall(r"^\s*\d+[.)]\s+(.*)$", body(7), re.MULTILINE)
        good = [i for i in items if not PLACEHOLDER.search(i) and len(words(i)) >= 3]
        measured["outline_points"] = len(good)
        res.add("A1", "PASS" if len(good) >= 5 else "FAIL",
                f"initial outline: {len(good)} numbered point(s) of 3+ words, 5 required")

    # E1-E8 — the AI exchanges
    exchanges = split_exchanges(body(8)) if body(8) is not None else None
    ex_ids = ("E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8")
    if exchanges is None:
        for cid in ex_ids:
            res.add(cid, "ERROR", "section 8 is missing")
    else:
        present = [e for e in EXCHANGES if e in exchanges]
        measured["exchanges"] = len(exchanges)
        absent = [e for e in EXCHANGES if e not in exchanges]
        res.add("E1", "FAIL" if absent else "PASS",
                f"exchanges found: {', '.join(sorted(exchanges)) or 'none'}"
                + (f" — missing {', '.join(absent)}" if absent else ""))

        prompts = {e: fenced_after(exchanges[e], "Prompt") for e in present}
        responses = {e: fenced_after(exchanges[e], "Response") for e in present}

        # E2 metadata
        probs = []
        models = []
        for e in present:
            block = exchanges[e]
            for key in ("Tool", "Model", "Date", "Purpose"):
                value = meta(block, key)
                if not value or PLACEHOLDER.search(value):
                    probs.append(f"{e} {key} empty")
            mp = model_problem(meta(block, "Model"))
            if mp and "empty" not in mp:
                probs.append(f"{e} model: {mp}")
            models.append(meta(block, "Model"))
            d = meta(block, "Date")
            if d and not PLACEHOLDER.search(d):
                if not ISO_DATE.match(d):
                    probs.append(f"{e} date {d!r} is not YYYY-MM-DD")
                else:
                    try:
                        day = date.fromisoformat(d)
                        if day.year != 2026:
                            probs.append(f"{e} date {d} is not in 2026")
                    except ValueError:
                        probs.append(f"{e} date {d!r} is not a real date")
        measured["model"] = models[0] if models else None
        if absent and not present:
            res.add("E2", "ERROR", "no exchanges to check")
        else:
            res.add("E2", "FAIL" if probs else "PASS",
                    "metadata: " + ("; ".join(probs) if probs else "tool, model, date and purpose on every exchange"))

        # E3 prompt + response present, responses long enough
        probs = []
        for e in present:
            p, r = prompts[e], responses[e]
            if not p or PLACEHOLDER.search(p) or len(words(p)) < 20:
                probs.append(f"{e} prompt missing or under 20 words")
            if not r or PLACEHOLDER.search(r):
                probs.append(f"{e} response missing")
            elif len(words(r)) < MIN_RESPONSE_WORDS[e]:
                probs.append(f"{e} response {len(words(r))} words — paste it complete "
                             f"(at least {MIN_RESPONSE_WORDS[e]} expected)")
        if not present:
            res.add("E3", "ERROR", "no exchanges to check")
        else:
            res.add("E3", "FAIL" if probs else "PASS",
                    "; ".join(probs) if probs else "every prompt and response pasted in full")

        # E4 anchors
        probs = []
        for e in present:
            p = norm(prompts[e])
            lost = [a for a in ANCHORS[e] if a not in p]
            if lost:
                probs.append(f"{e} prompt lost {len(lost)} fixed phrase(s), e.g. \"{lost[0]}\"")
        if not present:
            res.add("E4", "ERROR", "no exchanges to check")
        else:
            res.add("E4", "FAIL" if probs else "PASS",
                    "; ".join(probs) if probs else "Prompts A, B and C used as given")

        # E5 bracket fields
        probs = []
        for e in present:
            p = norm(prompts[e])
            left = [f for f in BRACKET_FIELDS if f in p]
            if left:
                probs.append(f"{e} still contains {', '.join(left)}")
        if not present:
            res.add("E5", "ERROR", "no exchanges to check")
        else:
            res.add("E5", "FAIL" if probs else "PASS",
                    "; ".join(probs) if probs else "every bracketed field replaced")

        # E6 Prompt A carries the scenario and the outline
        if "B1" not in present or body(1) is None or body(7) is None:
            res.add("E6", "ERROR", "Prompt A, section 1 or section 7 missing")
        else:
            pa = content_words(prompts["B1"])
            scen = content_words(" ".join(label_value(body(1), l) or "" for l in
                                          ("Users", "Problem", "Constraints", "Risk")))
            outline = content_words(body(7))
            s_hit, o_hit = len(scen & pa), len(outline & pa)
            ok = s_hit >= 4 and o_hit >= 4
            res.add("E6", "PASS" if ok else "FAIL",
                    f"Prompt A shares {s_hit} content word(s) with your scenario and {o_hit} with your "
                    f"outline (4+ each expected — paste them into the prompt)")

        # E7 / E8 the draft travels into B and C
        draft = shingles(responses.get("B1")) if "B1" in present else set()
        for cid, e, name in (("E7", "B2", "Prompt B"), ("E8", "B3", "Prompt C")):
            if e not in present or not draft:
                res.add(cid, "ERROR", f"{name} or the Prompt A response is missing")
                continue
            share = len(draft & shingles(prompts[e])) / len(draft)
            res.add(cid, "PASS" if share >= 0.3 else "FAIL",
                    f"{name} contains {share:.0%} of the Prompt A response (30%+ expected — "
                    f"the prompt says to paste the draft)")

    # V1-V3 verification table
    ver = table_after(body(9), "Verification table") if body(9) is not None else None
    if ver is None:
        for cid in ("V1", "V2", "V3"):
            res.add(cid, "ERROR", "section 9 or its ### Verification table heading is missing")
    else:
        complete = [r for r in ver if len(r) >= 4 and all(filled(c) for c in r[:4])]
        measured["verified_claims"] = len(complete)
        res.add("V1", "PASS" if len(complete) >= 2 else "FAIL",
                f"verification table: {len(complete)} complete row(s), 2 required")
        probs = []
        for i, r in enumerate(complete, 1):
            src = r[1]
            if not LOCATOR.search(src):
                probs.append(f"row {i} has no page / slide / section / chapter / URL")
            elif URL.search(src) and not ACCESS_DATE.search(src):
                probs.append(f"row {i} gives a URL with no access date")
        if not complete:
            res.add("V2", "FAIL", "no complete rows to check")
        else:
            res.add("V2", "FAIL" if probs else "PASS",
                    "; ".join(probs) if probs else "every row has a locator")
        tally = {d: 0 for d in DECISIONS}
        bad = []
        for i, r in enumerate(complete, 1):
            d = re.sub(r"[^a-z]", "", r[3].lower())
            if d in tally:
                tally[d] += 1
            else:
                bad.append(f"row {i}: {r[3]!r}")
        measured["decisions"] = tally
        if not complete:
            res.add("V3", "FAIL", "no complete rows to check")
        else:
            res.add("V3", "FAIL" if bad else "PASS",
                    ("decision must be keep, qualify or reject — " + "; ".join(bad)) if bad
                    else "decisions: " + ", ".join(f"{k} {v}" for k, v in tally.items()))

    # L1 change log
    log = table_after(body(9), "Change log") if body(9) is not None else None
    if log is None:
        res.add("L1", "ERROR", "section 9 or its ### Change log heading is missing")
    else:
        good, probs = 0, []
        for i, r in enumerate(log, 1):
            if len(r) < 3 or not all(filled(c) for c in r[:3]):
                continue
            if norm(r[0]) == norm(r[1]):
                probs.append(f"row {i}: final version identical to the AI wording")
            elif len(words(r[2])) < 4:
                probs.append(f"row {i}: reason under 4 words")
            else:
                good += 1
        measured["revisions"] = good
        verdict = "PASS" if good >= 2 else "FAIL"
        res.add("L1", verdict, f"change log: {good} substantive row(s), 2 required"
                + (" — " + "; ".join(probs) if probs else ""))

    # R1 references
    if body(6) is None:
        res.add("R1", "ERROR", "section 6 is missing")
    else:
        refs = [l.strip()[2:] for l in body(6).splitlines() if l.strip().startswith(("- ", "* "))]
        refs = [r for r in refs if r and not PLACEHOLDER.search(r) and len(words(r)) >= 4]
        measured["references"] = len(refs)
        probs = []
        if not refs:
            probs.append("no reference entries (one per line, starting with '- ')")
        ref_text = body(6).lower()
        for u in URL.findall(" ".join(r[1] for r in (ver or []) if len(r) > 1)):
            if u.lower().rstrip(".,;") not in ref_text:
                probs.append(f"{u} is in the verification table but not in References")
        res.add("R1", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else f"{len(refs)} reference(s); every table URL listed")

    # P1 leftovers anywhere
    left = PLACEHOLDER.findall(COMMENT.sub("", text))
    res.add("P1", "FAIL" if left else "PASS",
            f"{len(left)} template marker(s) like '(write here)' still in the file" if left
            else "no template markers left")

    return res, measured


def all_error(message):
    res = Results()
    for cid, _ in ALL_IDS:
        res.add(cid, "ERROR", message)
    return res


# --------------------------------------------------------------------------- output


def print_human(res, path):
    print(f"SIS #01 report checker — {path}")
    print("Checks SHAPE, never QUALITY.\n")
    names = dict(ALL_IDS)
    for r in res.rows:
        print(f"  {r['verdict']:<5}  {r['id']:<3} {names.get(r['id'], '')}")
        print(f"                {r['message']}")
    c = res.counts()
    print()
    print("Record these three numbers in submission.yml under checker:, with the commit hash")
    print("from `git rev-parse --short HEAD` — the commit this run was made at.")
    print(f"SUMMARY pass={c['PASS']} fail={c['FAIL']} error={c['ERROR']}")


def main():
    parser = argparse.ArgumentParser(description="Structural checker for SIS #01 report.md")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument("--file", default=REPORT, help="path to report.md (default: ./report.md)")
    args = parser.parse_args()

    if args.file == REPORT and not os.path.isdir("tests") and not os.path.exists(REPORT):
        msg = "run this from inside your sis-01/ folder:  cd sis-01 && python tests/check_report.py"
        print(json.dumps({"ok": False, "error": msg}) if args.json else "ERROR: " + msg)
        return 3

    if not os.path.exists(args.file):
        res, measured, code = all_error(f"{args.file} not found"), {}, 2
    else:
        text = open(args.file, encoding="utf-8", errors="replace").read()
        res, measured = check(text)
        c = res.counts()
        code = 0 if c["FAIL"] == 0 and c["ERROR"] == 0 else 1

    c = res.counts()
    if args.json:
        print(json.dumps({"ok": code == 0, "counts": c, "total": sum(c.values()),
                          "rows": res.rows, "measured": measured}, ensure_ascii=False, indent=2))
    else:
        print_human(res, args.file)
    return code


if __name__ == "__main__":
    sys.exit(main())
